{
 "title": "Kubernetes / Autoscaling / KEDA / Scaled Job",
 "description": "A dashboard that monitors KEDA Scaled Jobs. The dashboards were generated using [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "keda"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info{job=~\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "operator_namespace",
    "label": "Operator Namespace",
    "query": "label_values(keda_scaled_job_errors_total{cluster=\"$cluster\", job=~\"$job\"}, namespace)"
   },
   {
    "name": "resource_namespace",
    "label": "Resource Namespace",
    "query": "label_values(keda_scaled_job_errors_total{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\"}, exported_namespace)"
   },
   {
    "name": "scaled_job",
    "label": "Scaled Job",
    "query": "label_values(keda_scaled_job_errors_total{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\", exported_namespace=~\"$resource_namespace\"}, scaledJob)"
   },
   {
    "name": "scaler",
    "label": "Scaler",
    "query": "label_values(keda_scaler_active{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\", exported_namespace=\"$resource_namespace\", type=\"scaledjob\", scaledObject=\"$scaled_job\"}, scaler)"
   },
   {
    "name": "metric",
    "label": "Metric",
    "query": "label_values(keda_scaler_active{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\", exported_namespace=\"$resource_namespace\", type=\"scaledjob\", scaledObject=~\"$scaled_job\", scaler=~\"$scaler\"}, metric)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resources Registered by Namespace",
   "type": "timeseries",
   "description": "The number of scaled job resources registered by namespace.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_resource_registered_total{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=~\"$operator_namespace\",\n    type=\"scaled_job\"\n  }\n) by (exported_namespace, type)\n",
     "legendFormat": "{{ exported_namespace }} / {{ type }}"
    }
   ]
  },
  {
   "title": "Triggers by Type",
   "type": "timeseries",
   "description": "The number of triggers registered by type.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_trigger_registered_total{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=~\"$operator_namespace\"\n  }\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Scaled Jobs Errors",
   "type": "timeseries",
   "description": "The rate of errors for scaled jobs.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    keda_scaled_job_errors_total{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      namespace=~\"$operator_namespace\",\n      exported_namespace=~\"$resource_namespace\"\n    }[$__rate_interval]\n  )\n) by (exported_namespace, scaledJob)\n",
     "legendFormat": "{{ exported_namespace }} / {{ scaledJob }}"
    }
   ]
  },
  {
   "title": "Scaler Detail Errors",
   "type": "timeseries",
   "description": "The rate of scaler detail errors.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    keda_scaler_detail_errors_total{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      namespace=~\"$operator_namespace\",\n      exported_namespace=~\"$resource_namespace\",\n      type=\"scaledjob\"\n    }[$__rate_interval]\n  )\n) by (exported_namespace, scaledObject, scaler)\n",
     "legendFormat": "{{ exported_namespace }} / {{ scaledObject }} / {{ scaler }}"
    }
   ]
  },
  { "title": "Scaled Job Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Scaled Job Active",
   "type": "timeseries",
   "description": "Whether the scaled job is active.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaler_active{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=\"$operator_namespace\",\n    exported_namespace=\"$resource_namespace\",\n    type=\"scaledjob\",\n    scaledObject=\"$scaled_job\"\n  }\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ exported_namespace }} / {{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaled Job Detail Errors",
   "type": "timeseries",
   "description": "The rate of errors for the selected scaled job.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    keda_scaler_detail_errors_total{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      namespace=\"$operator_namespace\",\n      exported_namespace=\"$resource_namespace\",\n      type=\"scaledjob\",\n      scaledObject=\"$scaled_job\"\n    }[$__rate_interval]\n  )\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ exported_namespace }} / {{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaled Job Metric Value",
   "type": "timeseries",
   "description": "The metric value for the selected scaled job.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(\n  keda_scaler_metrics_value{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=\"$operator_namespace\",\n    exported_namespace=\"$resource_namespace\",\n    type=\"scaledjob\",\n    scaledObject=\"$scaled_job\",\n    scaler=\"$scaler\",\n    metric=\"$metric\"\n  }\n) by (exported_namespace, scaledObject, scaler, metric)\n",
     "legendFormat": "{{ exported_namespace }} / {{ scaledObject }} / {{ scaler }} / {{ metric }}"
    }
   ]
  },
  {
   "title": "Scaled Job Metric Latency",
   "type": "timeseries",
   "description": "The metric collection latency for the selected scaled job.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  keda_scaler_metrics_latency_seconds{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=\"$operator_namespace\",\n    exported_namespace=\"$resource_namespace\",\n    type=\"scaledjob\",\n    scaledObject=\"$scaled_job\",\n    scaler=\"$scaler\",\n    metric=\"$metric\"\n  }\n) by (exported_namespace, scaledObject, scaler, metric)\n",
     "legendFormat": "{{ exported_namespace }} / {{ scaledObject }} / {{ scaler }} / {{ metric }}"
    }
   ]
  },
  { "title": "Scale Targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Scale Target Values",
   "type": "table",
   "description": "Current metric values for all scaled jobs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaler_metrics_value{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=~\"$operator_namespace\",\n    exported_namespace=~\"$resource_namespace\",\n    type=\"scaledjob\"\n  }\n) by (job, exported_namespace, scaledObject, scaler, metric)\n"
    }
   ]
  }
 ]
}