{
 "title": "Kubernetes / Autoscaling / Vertical Pod Autoscaler",
 "description": "A dashboard that monitors Vertical Pod Autoscalers. The dashboards were generated using [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "vpa"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info{job=~\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kube_customresource_verticalpodautoscaler_labels{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_customresource_verticalpodautoscaler_labels{cluster=\"$cluster\", job=~\"$job\"}, namespace)"
   },
   {
    "name": "verticalpodautoscaler",
    "label": "Vertical Pod Autoscaler",
    "query": "label_values(kube_customresource_verticalpodautoscaler_labels{cluster=\"$cluster\", namespace=~\"$namespace\"}, verticalpodautoscaler)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{cluster=\"$cluster\", namespace=~\"$namespace\", verticalpodautoscaler=~\"$verticalpodautoscaler\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Namespace $namespace Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Resource Recommendations",
   "type": "table",
   "description": "CPU resource recommendations for VPAs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\n  label_replace(\n    max(\n      kube_pod_container_resource_requests{\n        cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n        resource=\"cpu\"\n      }\n    ) by (cluster, job, namespace, pod, container, resource),\n    \"verticalpodautoscaler\", \"$1\", \"pod\", \"^(.*?)(?:-[a-f0-9]{8,10}-[a-z0-9]{5}|-[0-9]+|-[a-z0-9]{5,16})$\"\n  )\n  + on(cluster, job, namespace, container, resource, verticalpodautoscaler) group_left()\n  0 *\n  max(\n    kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n      resource=\"cpu\"\n    }\n  ) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n)\nby (cluster, job, namespace, verticalpodautoscaler, container, resource)\n"
    },
    {
     "expr": "max(\n  label_replace(\n    max(\n      kube_pod_container_resource_limits{\n        cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n        resource=\"cpu\"\n      }\n    ) by (cluster, job, namespace, pod, container, resource),\n    \"verticalpodautoscaler\", \"$1\", \"pod\", \"^(.*?)(?:-[a-f0-9]{8,10}-[a-z0-9]{5}|-[0-9]+|-[a-z0-9]{5,16})$\"\n  )\n  + on(cluster, job, namespace, container, resource, verticalpodautoscaler) group_left()\n  0 *\n  max(\n    kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n      resource=\"cpu\"\n    }\n  ) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n)\nby (cluster, job, namespace, verticalpodautoscaler, container, resource)\n"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    resource=\"cpu\"\n  }\n) by (job, cluster, namespace, verticalpodautoscaler, container, resource)\n"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    resource=\"cpu\"\n  }\n) by (job, cluster, namespace, verticalpodautoscaler, container, resource)\n"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    resource=\"cpu\"\n  }\n) by (job, cluster, namespace, verticalpodautoscaler, container, resource)\n"
    }
   ]
  },
  {
   "title": "Memory Resource Recommendations",
   "type": "table",
   "description": "Memory resource recommendations for VPAs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n  label_replace(\n    max(\n      kube_pod_container_resource_requests{\n        cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n        resource=\"memory\"\n      }\n    ) by (cluster, job, namespace, pod, container, resource),\n    \"verticalpodautoscaler\", \"$1\", \"pod\", \"^(.*?)(?:-[a-f0-9]{8,10}-[a-z0-9]{5}|-[0-9]+|-[a-z0-9]{5,16})$\"\n  )\n  + on(cluster, job, namespace, container, resource, verticalpodautoscaler) group_left()\n  0 *\n  max(\n    kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n      resource=\"memory\"\n    }\n  ) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n)\nby (cluster, job, namespace, verticalpodautoscaler, container, resource)\n"
    },
    {
     "expr": "max(\n  label_replace(\n    max(\n      kube_pod_container_resource_limits{\n        cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n        resource=\"memory\"\n      }\n    ) by (cluster, job, namespace, pod, container, resource),\n    \"verticalpodautoscaler\", \"$1\", \"pod\", \"^(.*?)(?:-[a-f0-9]{8,10}-[a-z0-9]{5}|-[0-9]+|-[a-z0-9]{5,16})$\"\n  )\n  + on(cluster, job, namespace, container, resource, verticalpodautoscaler) group_left()\n  0 *\n  max(\n    kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n      resource=\"memory\"\n    }\n  ) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n)\nby (cluster, job, namespace, verticalpodautoscaler, container, resource)\n"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    resource=\"memory\"\n  }\n) by (job, cluster, namespace, verticalpodautoscaler, container, resource)\n"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    resource=\"memory\"\n  }\n) by (job, cluster, namespace, verticalpodautoscaler, container, resource)\n"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    resource=\"memory\"\n  }\n) by (job, cluster, namespace, verticalpodautoscaler, container, resource)\n"
    }
   ]
  },
  {
   "title": "$verticalpodautoscaler / $container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "container"
  },
  {
   "title": "CPU Guaranteed QoS",
   "type": "stat",
   "description": "CPU Guaranteed QoS recommendations (requests = limits) for the selected VPA.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"cpu\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"cpu\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "CPU Burstable QoS",
   "type": "stat",
   "description": "CPU Burstable QoS recommendations (requests < limits) for the selected VPA.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"cpu\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"cpu\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "Memory Guaranteed QoS",
   "type": "stat",
   "description": "Memory Guaranteed QoS recommendations (requests = limits) for the selected VPA.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"memory\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"memory\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "Memory Burstable QoS",
   "type": "stat",
   "description": "Memory Burstable QoS recommendations (requests < limits) for the selected VPA.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"memory\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"memory\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "VPA CPU Recommendations Over Time",
   "type": "timeseries",
   "description": "CPU recommendations, usage, requests, and limits over time for the selected VPA.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"cpu\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Lower Bound"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"cpu\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Target"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"cpu\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Upper Bound"
    },
    {
     "expr": "avg(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{\n    cluster=\"$cluster\",\n    namespace=~\"$namespace\",\n    pod=~\"$verticalpodautoscaler-.*\",\n    container=~\"$container\",\n    container!=\"\"\n  }\n) by (cluster, container)\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(\n  kube_pod_container_resource_requests{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    pod=~\"$verticalpodautoscaler-.*\",\n    resource=~\"cpu\",\n    container=~\"$container\"\n  }\n) by (cluster, container)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(\n  kube_pod_container_resource_limits{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    pod=~\"$verticalpodautoscaler-.*\",\n    resource=~\"cpu\",\n    container=~\"$container\"\n  }\n) by (cluster, container)\n",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "VPA Memory Recommendations Over Time",
   "type": "timeseries",
   "description": "Memory recommendations, usage, requests, and limits over time for the selected VPA.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"memory\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Lower Bound"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"memory\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Target"
    },
    {
     "expr": "max(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nverticalpodautoscaler=~\"$verticalpodautoscaler\",\ncontainer=~\"$container\"\n,\n    resource=\"memory\"\n  }\n) by (cluster, job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Upper Bound"
    },
    {
     "expr": "avg(\n  container_memory_working_set_bytes{\n    cluster=\"$cluster\",\n    namespace=~\"$namespace\",\n    pod=~\"$verticalpodautoscaler-.*\",\n    container=~\"$container\",\n    container!=\"\"\n  }\n) by (cluster, container)\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(\n  kube_pod_container_resource_requests{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    pod=~\"$verticalpodautoscaler-.*\",\n    resource=~\"memory\",\n    container=~\"$container\"\n  }\n) by (cluster, container)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(\n  kube_pod_container_resource_limits{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\n    pod=~\"$verticalpodautoscaler-.*\",\n    resource=~\"memory\",\n    container=~\"$container\"\n  }\n) by (cluster, container)\n",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}